name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build_linux:
    # Job name is Greeting
    name: Build on Linux
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build Binary
        run: ./build.sh
        shell: bash
  build_macosx:
    name: Build Mac OS X
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build Binary
        run: ./build.sh
        shell: bash