name: Build & Test
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags-ignore: v*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build Binary
        run: ./build.sh -j 8
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Prepare Python
        run: |
          python -m pip install --upgrade pip
          pip install nipype
          pip install -e ./Python/
        shell: bash
      - name: Run Tests
        run: export PATH="$PWD/../../build/Source:$PATH"; echo $PATH; python -m unittest discover
        working-directory: ./Python/Tests
        shell: bash
